version: "1.0"
info:
  model: int-scaffold
packages:
- name: BiswaPR1Project
  gitServerName: designerbvt
  gitUrl: https://github.com/designerbvt
  gitUsername: designerbvt
  gitBranch: main
- name: GlobalVariableDemo1
  gitServerName: designerbvt
  gitUrl: https://github.com/designerbvt
  gitUsername: designerbvt
  gitBranch: master
- name: GlobalVariableDemo2
  gitServerName: designerbvt
  gitUrl: https://github.com/designerbvt
  gitUsername: designerbvt
  gitBranch: master
- name: GlobalVariableDemo3
  gitServerName: designerbvt
  gitUrl: https://github.com/designerbvt
  gitUsername: designerbvt
  gitBranch: master
